### ISSUE TITLE
complie error with linux kernel 5.10

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8814au#18]
gentoo linux : kernel   gentoo-source-5.10.1
source complile error

**Comment by souravdas142** [comment]
Same error with kernel v5.10.3 see my log file
[make.log](https://github.com/aircrack-ng/rtl8814au/files/5757244/make.log)

**Comment by kminardo** [comment]
Arch Linux, v5.10.3, similar error

[make.log](https://github.com/aircrack-ng/rtl8814au/files/5757830/make.log)
