### ISSUE TITLE
DKMS build error on Debian 10

### ISSUE THREAD

**Issue by hardwareadictos** [aircrack-ng/rtl8814au#3]
Just having this error building on Debian 10:

  CC [M]  /var/lib/dkms/rtl8814au/5.8.5.1/build/8814au.mod.o
  LD [M]  /var/lib/dkms/rtl8814au/5.8.5.1/build/8814au.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.65-1-pve'
/usr/sbin/dkms: line 78: kmodsign: command not found

sbsigntool is installed, it has no sense to me.

Kernel: Linux atomikprometeus-dbn01 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux

Can someone help me please? Thanks in advance :)

Edit, full log attatched: 
[build_log.txt](https://github.com/aircrack-ng/rtl8814au/files/5401653/build_log.txt)

**Comment by kimocoder** [comment]
This is not a proper issue report. Need for info.. any info/output

**Comment by hardwareadictos** [comment]
> This is not a proper issue report. Need for info.. any info/output

Sorry, just published it accidentally before making the report

**Comment by kimocoder** [comment]
Your missing kmodsign.
More information here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939392

However, I'll add another DKMS install option without the kmodsign dependency shortly. I'll leave a note when done.

**Comment by hardwareadictos** [comment]
> Your missing kmodsign.
> More information here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939392
> 
> However, I'll add another DKMS install option without the kmodsign dependency shortly. I'll leave a note when done.

Thanks a lot :)

Let me know if you want me to test it first

**Comment by hardwareadictos** [comment]
Managed to delete kmodsign references on code, recompiled and driver just got installed:

root@atomikprometeus-dbn01:~# grep -ir kmodsign rtl8814au
rtl8814au/debian/changelog:  * add kmodsign
rtl8814au/debian/changelog.in:  * add kmodsign
rtl8814au/debian/rtl8814au-dkms.dkms.debhelper:MAKE="'make' clean; 'make' all;kmodsign sha512 MOK.priv MOK.der 8814au.ko"
rtl8814au/debian/rtl8814au-dkms.dkms:MAKE="'make' clean; 'make' all;kmodsign sha512 MOK.priv MOK.der 8814au.ko"
rtl8814au/debian/rtl8814au-dkms/usr/src/rtl8814au-5.8.5.1/dkms.conf:MAKE="'make' clean; 'make' all;kmodsign sha512 MOK.priv MOK.der 8814au.ko"

root@atomikprometeus-dbn01:~# dpkg -i rtl8814au-dkms_5.8.5.1_all.deb
(Reading database ... 102117 files and directories currently installed.)
Preparing to unpack rtl8814au-dkms_5.8.5.1_all.deb ...

Deleting module version: 5.8.5.1
completely from the DKMS tree.

Done.
Unpacking rtl8814au-dkms (5.8.5.1) over (5.8.5.1) ...
Setting up rtl8814au-dkms (5.8.5.1) ...
Loading new rtl8814au-5.8.5.1 DKMS files...
Building for 5.4.65-1-pve
Building initial module for 5.4.65-1-pve
Done.

8814au.ko:
Running module version sanity check.
 Original module
 No original module exists within this kernel
 Installation
 Installing to /lib/modules/5.4.65-1-pve/updates/dkms/

depmod...

DKMS: install completed.

Seems its on system:

root@atomikprometeus-dbn01:~# lsmod | grep 88
8814au               2166784  0
cfg80211              704512  1 8814au
btrfs                1241088  0
raid6_pq              114688  4 async_pq,btrfs,raid456,async_raid6_recov

But no leds powering up or interface detected on Debian. Maybe i'm missing something, not an expert on Wireless LAN drivers :P

**Comment by kimocoder** [comment]
Ok. I also updated the DKMS install script,

$ make dkms_install
and
$ make dkms_remove

Is the commands.
